#!/usr/bin/env bash
# gen-design-index.sh — Generate docs/design-decisions/index.md from frontmatter in each design decision file.
# Usage: bash scripts/gen-design-index.sh [--root <project-root>]
#
# Compatible with bash 3.2+ (macOS default).

set -euo pipefail

ROOT="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

DECISIONS_DIR="$ROOT/docs/design-decisions"
INDEX_FILE="$DECISIONS_DIR/index.md"

if [[ ! -d "$DECISIONS_DIR" ]]; then
  echo "Error: $DECISIONS_DIR does not exist." >&2
  exit 1
fi

# 从文件中提取 frontmatter 字段值
get_field() {
  local file="$1" field="$2"
  awk -v f="$field" '
    /^---$/ { if (found++) exit }
    $0 ~ "^" f ": " {
      sub("^" f ": ", "")
      gsub(/^[[:space:]]*"|"[[:space:]]*$/, "")
      print
      exit
    }
  ' "$file"
}

# 从文件名中提取日期：YYYY-MM-DD-*.md
get_date() {
  basename "$1" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
}

# 转义 Markdown 表格中的 | 字符，防止列错位
escape_pipe() {
  echo "${1//|/\\|}"
}

# 收集所有设计文档（按文件名排序，日期前缀 = 时间顺序）
FILES=()
while IFS= read -r f; do
  FILES+=("$f")
done < <(find "$DECISIONS_DIR" -maxdepth 1 -name "*.md" \
  ! -name "index.md" ! -name "_template.md" | sort)

TOTAL=${#FILES[@]}
if [[ $TOTAL -eq 0 ]]; then
  echo "No design decision files found in $DECISIONS_DIR" >&2
  exit 0
fi

# --- 超越关系一致性检查 ---
WARN=0
for f in "${FILES[@]}"; do
  fname=$(basename "$f")
  supersedes=$(get_field "$f" "supersedes")
  superseded_by=$(get_field "$f" "superseded_by")

  if [[ -n "$supersedes" ]]; then
    target="$DECISIONS_DIR/$supersedes"
    if [[ ! -f "$target" ]]; then
      echo "WARNING: $fname: supersedes '$supersedes' — file not found." >&2
      WARN=1
    else
      reverse=$(get_field "$target" "superseded_by")
      if [[ "$reverse" != "$fname" ]]; then
        echo "WARNING: $fname: supersedes '$supersedes' but that file has superseded_by='$reverse' (expected '$fname')." >&2
        WARN=1
      fi
    fi
  fi

  if [[ -n "$superseded_by" ]]; then
    target="$DECISIONS_DIR/$superseded_by"
    if [[ ! -f "$target" ]]; then
      echo "WARNING: $fname: superseded_by '$superseded_by' — file not found." >&2
      WARN=1
    fi
  fi
done

# 索引表格最大行数
MAX_ROWS=100

# --- 生成 index.md ---
{
  cat <<'HEADER'
# Design Decisions Index

> This file is auto-generated by `gen-design-index.sh`. Do not edit manually.
> Run: `bash scripts/gen-design-index.sh --root <project-root>`
>
> **Status values:**
> `Active` — in progress or adopted, pending implementation
> `Implemented` — fully implemented
> `Superseded` — replaced by a newer design (see note column)
> `Archived` — no longer applicable

---

HEADER

  echo "| File | Area | Status | Date | Description | Note |"
  echo "|------|------|--------|------|-------------|------|"

  # 按文件名降序（日期前缀 = 最新在前），最多输出 MAX_ROWS 行
  ROW=0
  while IFS= read -r f; do
    [[ $ROW -ge $MAX_ROWS ]] && break
    fname=$(basename "$f")
    title=$(escape_pipe "$(get_field "$f" "title")")
    area=$(get_field "$f" "area")
    status=$(get_field "$f" "status")
    date=$(get_date "$f")
    description=$(escape_pipe "$(get_field "$f" "description")")
    supersedes=$(get_field "$f" "supersedes")
    superseded_by=$(get_field "$f" "superseded_by")

    note=""
    [[ -n "$supersedes" ]] && note="supersedes [↑]($supersedes)"
    [[ -n "$superseded_by" ]] && note="superseded by [↓]($superseded_by)"
    note=$(escape_pipe "$note")

    echo "| [$title]($fname) | $area | $status | $date | $description | $note |"
    ROW=$((ROW + 1))
  done < <(printf '%s\n' "${FILES[@]}" | sort -r)

  echo ""
} > "$INDEX_FILE"

echo "Generated: $INDEX_FILE ($TOTAL files)"
[[ $WARN -eq 1 ]] && echo "Warnings reported above — fix supersedes/superseded_by consistency." >&2

exit 0
